/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxIdRouteImport } from './routes/sandbox.$id'
import { Route as ApiSandboxRouteImport } from './routes/api/sandbox'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSandboxIdRouteImport } from './routes/api/sandbox.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxIdRoute = SandboxIdRouteImport.update({
  id: '/sandbox/$id',
  path: '/sandbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxRoute = ApiSandboxRouteImport.update({
  id: '/api/sandbox',
  path: '/api/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxIdRoute = ApiSandboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSandboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sandbox': typeof ApiSandboxRouteWithChildren
  '/sandbox/$id': typeof SandboxIdRoute
  '/api/sandbox/$id': typeof ApiSandboxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sandbox': typeof ApiSandboxRouteWithChildren
  '/sandbox/$id': typeof SandboxIdRoute
  '/api/sandbox/$id': typeof ApiSandboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sandbox': typeof ApiSandboxRouteWithChildren
  '/sandbox/$id': typeof SandboxIdRoute
  '/api/sandbox/$id': typeof ApiSandboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/sandbox'
    | '/sandbox/$id'
    | '/api/sandbox/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/sandbox' | '/sandbox/$id' | '/api/sandbox/$id'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/sandbox'
    | '/sandbox/$id'
    | '/api/sandbox/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSandboxRoute: typeof ApiSandboxRouteWithChildren
  SandboxIdRoute: typeof SandboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/$id': {
      id: '/sandbox/$id'
      path: '/sandbox/$id'
      fullPath: '/sandbox/$id'
      preLoaderRoute: typeof SandboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox': {
      id: '/api/sandbox'
      path: '/api/sandbox'
      fullPath: '/api/sandbox'
      preLoaderRoute: typeof ApiSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox/$id': {
      id: '/api/sandbox/$id'
      path: '/$id'
      fullPath: '/api/sandbox/$id'
      preLoaderRoute: typeof ApiSandboxIdRouteImport
      parentRoute: typeof ApiSandboxRoute
    }
  }
}

interface ApiSandboxRouteChildren {
  ApiSandboxIdRoute: typeof ApiSandboxIdRoute
}

const ApiSandboxRouteChildren: ApiSandboxRouteChildren = {
  ApiSandboxIdRoute: ApiSandboxIdRoute,
}

const ApiSandboxRouteWithChildren = ApiSandboxRoute._addFileChildren(
  ApiSandboxRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSandboxRoute: ApiSandboxRouteWithChildren,
  SandboxIdRoute: SandboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
